### ISSUE TITLE
High priority vulnerability: @frctl/nunjucks

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-pattern-library#108]
This high priority vulnerability was found through the `@frctl/nunjucks` dependency of `qs`. By upgrading 2 patched versions from 1.0.1 to 1.0.3 should fix this vulnerability. 

**Completion criteria:**
- [ ] Upgrade package.json for `frctl/nunjucks` locally and test the upgraded version. If no issues, we should upgrade
- [ ] Submit a PR to upgrade the version

**Comment by lbeaufort** [comment]
PR merged - thanks @JonellaCulmer!
