### ISSUE TITLE
Add highlight component to the pattern library

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-pattern-library#112]
**What we're after:** 
Add "Highlight" as a component in the pattern library

**Why we're after it:** We use highlighting in different places on the website to call attention to specific words in MUR search results and to call attention to example text in reporting examples. We need to add this pattern to the pattern library to make sure that if/when we need to implement highlighting in the future that it is implemented properly, and for the right reasons. 

**Component preview mockup**
These should include the following examples:
<img width="1182" alt="screen shot 2018-04-20 at 12 53 56 pm" src="https://user-images.githubusercontent.com/31663028/39070176-4cb73aba-44b0-11e8-9f56-47c91be5c736.png">
<img width="969" alt="screen shot 2018-04-20 at 12 54 32 pm" src="https://user-images.githubusercontent.com/31663028/39070185-5259d7b6-44b0-11e8-8167-5d60ecac7191.png">

**Content for notes tab**
> Highlighting draws attention to particular information in long string of text or complicated image. Their color is dependent on their placement within the architecture of the website. For example, highlighting used within the Help for candidates and committees section of the website will be orange, and for the Legal resources section aqua will be used.
> _Ex: [Joint contributions](https://www.fec.gov/help-candidates-and-committees/filing-reports/joint-contributions/)_
>

**Comment by jenniferthibault** [comment]
@JonellaCulmer I finally settled on what felt off to me here, thanks for the time to think through it. I'd be curious to hear your feedback on the framing below!
___

The reporting example image here feels different to me because it's not a code-based implementation of the component that could be repeated. It feels like an image style that has to be made outside of the code structure, so I'd be inclined to drop the image from the examples. 

Here's how I might edit the writeup to describe the component as I understand it:

> Text highlighting allows users to see their search term in context of the text surrounding it to help determine if they've found what they're looking for. Text highlighting draws attention to a word or phrase that has been searched for when the results are formatted as text excerpted from a larger whole. The style applies a bold weight to the text that matches the search terms, and adds an accent-colored background fill to the shape of the word. This combination of changes helps distinguish the match from the rest of the search result content. 

> ## When to use:
> - In partnership with a keyword search field, or other free text search filters
      _Ex: [MUR keyword search](https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=legal&mur_no=&mur_respondents=)_
> - When results scan and display the body content from pages or documents to match keyword search filters, and users need help identifying the matches in context.
     _Ex: [Search results](https://www.fec.gov/search/?query=foreign&type=candidates&type=committees&type=site)_

**Comment by JonellaCulmer** [comment]
@jenniferthibault That makes sense. They are different implementations and should be distinguished. I still believe, though, that the reporting example highlighting should be addressed in this pattern since the intention is the same. While not to highlight a specific searched word, but to draw attention to key pieces of information.
