### ISSUE TITLE
[Low risk] Two vulnerabilities introduced through @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-pattern-library#117]
Update 7/12/18 - these issues remain:
- [braces](https://snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e/?severity=low#npm:braces:20180219) 
Regular Expression Denial of Service (ReDoS)
Vulnerable module: braces
Introduced through: @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3
Remediation: No remediation path available.
- [lodash](https://snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e/?severity=low#npm:lodash:20180130) Prototype Pollution
Vulnerable module: lodash
Introduced through: @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3
Remediation: No remediation path available.

These have been addressed: 
~[debug](https://snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e/?severity=low#npm:debug:20170905)
Regular Expression Denial of Service (ReDoS)
Vulnerable module: debug
Introduced through: @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3
Remediation: Run snyk wizard to patch debug
[ms](https://snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e/?severity=low#npm:ms:20170412) 
Regular Expression Denial of Service (ReDoS)
Vulnerable module: ms
Introduced through: @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3
Remediation: Run snyk wizard to patch ms
[hoek](https://snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e/?severity=low#npm:hoek:20180212) 
Prototype Pollution
Vulnerable module: hoek
Introduced through: @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3
Remediation: No remediation path available.~

**Comment by patphongs** [comment]
4 of these low risk vulnerabilities have been remediated with this PR: https://github.com/fecgov/fec-pattern-library/pull/119

SNYK tests have been re-run to confirm.

Outstanding low risk vulnerabilities still include:

- [lodash](https://snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e/?severity=low#npm:lodash:20180130) Prototype Pollution
Vulnerable module: lodash
Introduced through: @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3
Remediation: No remediation path available.
- [braces](https://snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e/?severity=low#npm:braces:20180219) 
Regular Expression Denial of Service (ReDoS)
Vulnerable module: braces
Introduced through: @frctl/fractal@1.1.7 and @frctl/nunjucks@1.0.3
Remediation: No remediation path available.

**Comment by patphongs** [comment]
resolved in PR #129
