### ISSUE TITLE
Test stage: Test candidate linkage on committee page

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-pattern-library#118]
https://github.com/fecgov/fec-cms/issues/1476

Are there show stoppers?

**Comment by AmyKort** [comment]
For real, this looked good to me. I haven't found a situation where the linkage was improper or missing. It shows appropriately on pages where there is no data to report as well. The pattern matches what is described in the ticket. Thanks!

**Comment by patphongs** [comment]
Thanks @AmyKort! I'm closing this issue now that you have confirmed it is good to go!

**Comment by patphongs** [comment]
Issue moved to [fecgov/fec-cms #1957](https://github.com/fecgov/fec-cms/issues/1957) via [**ZenHub**](https://www.zenhub.com/)
