### ISSUE TITLE
[MED] chownr - Time of Check Time of Use (TOCTOU) (Due 09/30/18)

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-pattern-library#127]
Check logs sprint 6.5 (Penny Robinson) week 2 #3301 found following issue:

https://app.snyk.io/org/fecgov/project/0e33b068-0c21-4956-8f86-a63eec4b306e

Vulnerable module: chownr
Introduced through: @frctl/nunjucks@1.0.3 and @frctl/fractal@1.1.7

No remediation path

**Comment by patphongs** [comment]
Check @apburnes PR https://github.com/fecgov/fec-pattern-library/pull/129, will have justifications for JS vulnerabilities dealing with fractl.

**Comment by patphongs** [comment]
Closing this issue since PR #129 took care of this for us
