### ISSUE TITLE
We need to Update manifests to specify cflinuxfs2 stack before release

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-pattern-library#130]
We need to Update manifests to specify cflinuxfs2 stack before release

testing cflinuxfs2:
1. add cflinuxfs2 to manifest.yml file:

---
path: ./docs
stack: cflinuxfs2
applications:
- name: fec-pattern-library
  memory: 64M
  buildpack: staticfile_buildpack
  env:
    FORCE_HTTPS: true

2. install packages and build the app to make sure everything is ok:
>>npm install
>>npm run build
>>npm run start

3. id everything is ok, login to cloud.gov dev space: 
>> cf login -u <user_name> -a api.fr.cloud.gov  --sso

4. do a 'cf push' to deploy:
>>cf push fec-pattern-library -f manifest.yml

**Comment by patphongs** [comment]
@qqss88 and @pkfec paired with me on what to do to push the new cflinuxfs3 stack. Let me know if you need any more help, thanks!

**Comment by qqss88** [comment]
deployment is working, but some waning messages comes back:

Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: path, stack.
Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.


Downloaded app package (7.6M)
-----> Staticfile Buildpack version 1.4.39
       **WARNING** buildpack version changed from 1.4.37 to 1.4.39
-----> Installing nginx
       Using nginx version 1.15.8
-----> Installing nginx 1.15.8
       Copy [/tmp/cache/final/dependencies/f4f7dadc3bf738eb96aa60852de5c955980c40bd3031c8caf46bc1fe842f5ce7/nginx-1.15.8-linux-x64-cflinuxfs2-48b8f057.tgz]
-----> Root folder /tmp/app
-----> Copying project files into public
-----> Configuring nginx
       **WARNING** overriding nginx.conf is deprecated and highly discouraged, as it breaks the functionality of the Staticfile and Staticfile.auth configuration directives. Please use the NGINX buildpack available at: https://github.com/cloudfoundry/nginx-buildpack

**Comment by qqss88** [comment]
modify the deploy script to do a push instead of zero-downtime-push. The command line is like this:

./bin/cf_deploy.sh fec-pattern-library fec-beta-fec dev manifest.yml

**Comment by qqss88** [comment]
+ cloud_gov=https://api.fr.cloud.gov
+ app=fec-pattern-library
+ org=fec-beta-fec
+ space=dev
+ manifest=manifest.yml
+ [[ -z fec-beta-fec ]]
+ [[ -z dev ]]
+ [[ -z fec-pattern-library ]]
+ cf api https://api.fr.cloud.gov
Setting api endpoint to https://api.fr.cloud.gov...
OK

api endpoint:   https://api.fr.cloud.gov
api version:    2.131.0
+ set +x
+ cf target -o fec-beta-fec -s dev
api endpoint:   https://api.fr.cloud.gov
api version:    2.131.0
user:           qsun.ctr@fec.gov
org:            fec-beta-fec
space:          dev
+ command=push
+ cf push fec-pattern-library -f manifest.yml
Pushing from manifest to org fec-beta-fec / space dev as qsun.ctr@fec.gov...
Using manifest file manifest.yml

Using manifest file manifest.yml

Using stack cflinuxfs2...
OK
Updating app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
OK

Uploading fec-pattern-library...
Uploading app files from: /Users/qsun.ctr/workspace/FEC/fec-pattern-library/docs
Uploading 2.7M, 458 files
Done uploading
OK

Stopping app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
OK

Starting app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
Downloading staticfile_buildpack...
Downloaded staticfile_buildpack (5M)
Cell 6d95d13f-dc29-4fcc-b9fd-58d935fcd8ab creating container for instance 9d7c32cd-8b76-4857-b04e-6905fcabf418
Cell 6d95d13f-dc29-4fcc-b9fd-58d935fcd8ab successfully created container for instance 9d7c32cd-8b76-4857-b04e-6905fcabf418
Downloading app package...
Downloading build artifacts cache...
Downloaded build artifacts cache (2.7M)
Downloaded app package (7.6M)
-----> Staticfile Buildpack version 1.4.39
-----> Installing nginx
       Using nginx version 1.15.8
-----> Installing nginx 1.15.8
       Copy [/tmp/cache/final/dependencies/f4f7dadc3bf738eb96aa60852de5c955980c40bd3031c8caf46bc1fe842f5ce7/nginx-1.15.8-linux-x64-cflinuxfs2-48b8f057.tgz]
-----> Root folder /tmp/app
-----> Copying project files into public
-----> Configuring nginx
       **WARNING** overriding nginx.conf is deprecated and highly discouraged, as it breaks the functionality of the Staticfile and Staticfile.auth configuration directives. Please use the NGINX buildpack available at: https://github.com/cloudfoundry/nginx-buildpack

Exit status 0
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploading build artifacts cache...
Uploaded build artifacts cache (2.7M)
Uploaded droplet (10.2M)
Uploading complete
Cell 6d95d13f-dc29-4fcc-b9fd-58d935fcd8ab stopping instance 9d7c32cd-8b76-4857-b04e-6905fcabf418
Cell 6d95d13f-dc29-4fcc-b9fd-58d935fcd8ab destroying container for instance 9d7c32cd-8b76-4857-b04e-6905fcabf418
Cell 6d95d13f-dc29-4fcc-b9fd-58d935fcd8ab successfully destroyed container for instance 9d7c32cd-8b76-4857-b04e-6905fcabf418

1 of 1 instances running

App started


OK

App fec-pattern-library was started using this command `$HOME/boot.sh`

Showing health and status for app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
OK

requested state: started
instances: 1/1
usage: 64M x 1 instances
urls: fec-pattern-library.app.cloud.gov
last uploaded: Mon Mar 11 15:00:34 UTC 2019
stack: cflinuxfs2
buildpack: staticfile_buildpack

     state     since                    cpu    memory        disk          details
#0   running   2019-03-11 11:00:57 AM   0.0%   2.8M of 64M   23.5M of 1G

**Comment by qqss88** [comment]
running deploy script with cflinuxfs3 is ok and got the same result:
+ cloud_gov=https://api.fr.cloud.gov
+ app=fec-pattern-library
+ org=fec-beta-fec
+ space=dev
+ manifest=manifest.yml
+ [[ -z fec-beta-fec ]]
+ [[ -z dev ]]
+ [[ -z fec-pattern-library ]]
+ cf api https://api.fr.cloud.gov
Setting api endpoint to https://api.fr.cloud.gov...
OK

api endpoint:   https://api.fr.cloud.gov
api version:    2.131.0
+ set +x
+ cf target -o fec-beta-fec -s dev
api endpoint:   https://api.fr.cloud.gov
api version:    2.131.0
user:           qsun.ctr@fec.gov
org:            fec-beta-fec
space:          dev
+ command=push
+ cf push fec-pattern-library -f manifest.yml
Pushing from manifest to org fec-beta-fec / space dev as qsun.ctr@fec.gov...
Using manifest file manifest.yml


Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: path, stack.
Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.


Using manifest file manifest.yml

Using stack cflinuxfs3...
OK
Updating app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
OK

Uploading fec-pattern-library...
Uploading app files from: /Users/qsun.ctr/workspace/FEC/fec-pattern-library/docs
Uploading 2.7M, 458 files
Done uploading
OK

Stopping app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
OK

Starting app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
Downloading staticfile_buildpack...
Downloaded staticfile_buildpack (5M)
Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 creating container for instance 5a371a53-1029-4d82-b62a-506086e1c987
Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 successfully created container for instance 5a371a53-1029-4d82-b62a-506086e1c987
Downloading app package...
Downloaded app package (7.6M)
-----> Staticfile Buildpack version 1.4.39
-----> Installing nginx
       Using nginx version 1.15.8
-----> Installing nginx 1.15.8
       Download [https://buildpacks.cloudfoundry.org/dependencies/nginx-static/nginx-1.15.8-linux-x64-cflinuxfs3-6f865593.tgz]
-----> Root folder /tmp/app
-----> Copying project files into public
-----> Configuring nginx
       **WARNING** overriding nginx.conf is deprecated and highly discouraged, as it breaks the functionality of the Staticfile and Staticfile.auth configuration directives. Please use the NGINX buildpack available at: https://github.com/cloudfoundry/nginx-buildpack
Exit status 0
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploading build artifacts cache...
Uploaded build artifacts cache (1.9M)
Uploaded droplet (9.5M)
Uploading complete
Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 stopping instance 5a371a53-1029-4d82-b62a-506086e1c987
Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 destroying container for instance 5a371a53-1029-4d82-b62a-506086e1c987
Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 successfully destroyed container for instance 5a371a53-1029-4d82-b62a-506086e1c987

1 of 1 instances running

App started

OK

App fec-pattern-library was started using this command `$HOME/boot.sh`

Showing health and status for app fec-pattern-library in org fec-beta-fec / space dev as qsun.ctr@fec.gov...
OK

requested state: started
instances: 1/1
usage: 64M x 1 instances
urls: fec-pattern-library.app.cloud.gov
last uploaded: Mon Mar 11 15:14:27 UTC 2019
stack: cflinuxfs3
buildpack: staticfile_buildpack

     state     since                    cpu    memory        disk          details
#0   running   2019-03-11 11:14:48 AM   0.0%   2.9M of 64M   22.8M of 1G

**Comment by JonellaCulmer** [comment]
This done so closing.
