### ISSUE TITLE
Vulnerable module: jquery in package.json medium (from check logs)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-pattern-library#133]
package.json 1 medium
Vulnerable module: jquery
Introduced through: datatables.net-responsive@2.0.1, typeahead.js@0.11.1 and others
[https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006](https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006)

**Comment by lbeaufort** [comment]
Snyk is no longer flagging this vulnerability.
