### ISSUE TITLE
Github vulnerabilities

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-pattern-library#158]
Take a look at the PRs opened by GitHub bots, Github security alerts

**Comment by rfultz** [comment]
Currently there are two outstanding PRs, #152 and #154 

- #152 : I think it's fine—it's just a dev dependency-dependency-dependency. I [commented](https://github.com/fecgov/fec-pattern-library/pull/152#issuecomment-640698484)
- #154 : This one's only used by Snyk so I can't really test. My [comment](https://github.com/fecgov/fec-pattern-library/pull/154#issuecomment-640692465)
