### ISSUE TITLE
Add color pairing guidance to Color documentation page

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-pattern-library#39]
So that designers know how to use color combinations, add the color pairings for etext and icons section to the [Color documentation page](https://fec-pattern-library.app.cloud.gov/docs/colors.html)

🖼 [InVision designs](https://gsa.invisionapp.com/share/FDC5XMYKB#/238949400_Colors)

Preview:
![screen shot 2017-11-30 at 9 37 43 am](https://user-images.githubusercontent.com/11636908/33436199-6c79d064-d5b2-11e7-866e-0ea2ce25f4d0.png)

(UPDATE: we've got a PR in and next steps are to address a few outstanding comments)

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by jenniferthibault** [comment]
Not quite yet @AmyKort thanks for checking in!  Pat's PR https://github.com/18F/fec-pattern-library/pull/44 has been reviewed, and there are some outstanding comments for her to address once she gets back.

**Comment by AmyKort** [comment]
Should we re-prioritize this?

**Comment by patphongs** [comment]
@AmyKort That's been on my radar, but unfortunately I haven't had time to fully wrap this one up. I kind of don't want to keep it lagging behind, but can we make it something for 5.2 since I already have a PR that needs tweaks?

**Comment by PaulClark2** [comment]
One of our PI goals is to not let issues slip from sprint to sprint.  Can someone with a lighter load this sprint wrap-up this work? Can someone pick-up some of your current work to give to time to wrap up the PR?

If these aren’t options, is this work still a priority above other work scheduled for S 5.2? We’ll need to think about what gets removed from S5.2.

**Comment by jenniferthibault** [comment]
@patphongs this was moved back into 5.3 and assigned at sprint planning today. Your work in the PR looks really close, let me know if I can pair with you to help finish it up 👯

**Comment by jenniferthibault** [comment]
Resolved by #105
