### ISSUE TITLE
Transfer fec-pattern-library GitHub repo to FEC

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-pattern-library#51]
- [x]  [fec-pattern-library](https://github.com/18F/fec-pattern-library)
    - [x]  set up circle 
    - [x] set up gemnasium alerts

**Comment by AmyKort** [comment]
@LindsayYoung and @ccostino

**Comment by LindsayYoung** [comment]
Done Marked this on the master list too https://github.com/fecgov/fec-transition/issues/155
