### ISSUE TITLE
Adjust breadcrumbs component to be comprehensive by showing a second example

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-pattern-library#56]
👯 **Pairing/training opportunity!** 👯 

_Filed as a next step to #47_

To complete the examples of the breadcrumbs component, show an example with a crimson background.

**Current state in the pattern library:**
![screen shot 2018-02-23 at 10 31 15 pm](https://user-images.githubusercontent.com/11636908/36625239-f4254d20-18e9-11e8-8586-74e5410e044c.png)

**Updated and comprehensive state:**
![screen shot 2018-02-23 at 10 29 41 pm](https://user-images.githubusercontent.com/11636908/36625245-08f92546-18ea-11e8-83ae-e05b5de417af.png)

Completion criteria for updating pattern:
- [x] Add example of breadcrumbs from Help for candidates and committees

**Comment by patphongs** [comment]
@jenniferthibault I went ahead and took at stab at this. I didn't add the additional white space between the primary and secondary breadcrumbs as I would have had to accomplish that using inline styles. Do you feel that it necessary? PR is here ready for your review: https://github.com/fecgov/fec-pattern-library/pull/97

**Comment by jenniferthibault** [comment]
Left a comment on the PR, but carrying it here as well— as Christine noted in her PR review https://github.com/fecgov/fec-pattern-library/pull/44#issuecomment-348578226

It's definitely ok to use inline styling to make renderings of multiple component examples more clear.

**Comment by jenniferthibault** [comment]
Resolved by implementation in #97
