### ISSUE TITLE
Determine if banner component can be removed

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-pattern-library#70]
👯 **Learning/pairing opportunity!** 👯 

_Filed as a next step to #47_

**What we're after:** Taking next step from the audit in #46 to make sure the pattern library is up to date and accurate by only including patterns that are part of the site's current or future intentions. 

**Why we're after it:** Including outdated components, or components without strong use cases makes more clutter and confusion for designers and developers considering their options.

___

Identified in the component audit of #46, the banner component stood out as one no longer in use on the site.

The [banner component](https://fec-pattern-library.app.cloud.gov/components/detail/banner.html) was designed while the beta site and new site were transitioning and needed numerous announcements in a consistent location across all site instances —beta (now new), transition, classic. This banner allowed us to place those communications in a universal and expected location.

![screen shot 2018-02-26 at 5 40 37 pm](https://user-images.githubusercontent.com/11636908/36699915-31301ff4-1b1c-11e8-9489-9296bcca1274.png)

Now, we haven't had a similar use case since then, and have developed a different approach to delivering time-sensitive information on the home page, by making use of the daily alerts or the urgent notice banner in rare instances. That makes me think the universal banner component won't be put to use again in the future.

**Completion criteria:**
- [ ] Outline options
- [ ] Design team discusses (on GitHub or in design pairing) and makes a decision
- [ ] New issue is filed for work based on the decision

**Comment by jenniferthibault** [comment]
I didn't want to bias the issue-writing too much, so here's where I see some options for this component:

- If we thought there was a use case in the future, we could keep it, and use the `Not in use` label. 
- If the component does conflict with the new and different strategy in use on the home page, it might be appropriate to retire this component and remove it from the library completely.

**Comment by patphongs** [comment]
As I recall, this was a collapsible banner that we used for the site tour. Here's my 2 cents: the site tour was retired, and so should this banner. The new banner component we have on the homepage should be sufficient enough for our banner needs.

**Comment by JonellaCulmer** [comment]
I agree that keeping it in the pattern library will contribute to clutter and confusion as to what patterns can be used to address any given usability or visual design needs in the future. 

However, I wonder if it's possible to still keep track of the information regarding that component (notes, html, etc), so _just in case_ we need to revisit the details of that component we have that information stored somewhere. Perhaps it's something as simple as a google doc?

**Comment by jenniferthibault** [comment]
@JonellaCulmer for that scenario where 
- it's not an active element on the site, 
- you don't think you'd use it again in the future
- but you don't want to lose track of the work that went into it

I'd keep the component in your sketch files, but delete it from the pattern repo. If there's any documentation or brief notes you want to leave, you could also leave that in the Sketch file for yourself. 
(Right now you'll find this banner and more from the onboarding experience design in the `FEC_components.sketch` file under "Banner") That way if you might need it again, you'll have the tools to mock up how you'd use it in your Sketch file.

A google doc would work too! Just worried about removing documentation from one place only to add it in another that you need to track. But use whatever system works best for you

**Comment by jenniferthibault** [comment]
@patphongs the other way this banner was used was on Staging and Dev to help people know what environment they were on. Originally designed here, but also doesn't seem to be in use anymore: https://github.com/fecgov/openFEC/issues/1216


![Image of banner on staging](https://cloud.githubusercontent.com/assets/11636908/10370406/a181cfca-6dac-11e5-8c23-e9ab0a4b0148.png)

**Comment by patphongs** [comment]
@jenniferthibault Oh yea! I completely forgot about that! I wonder if it would be good to leave this pattern then. I do find it useful to have that banner there to tell the user which environment they are looking at. We should investigate why that isn't showing up anymore...

**Comment by patphongs** [comment]
We've decided that this should be removed from the pattern library since this is a unique banner in staging, dev, and stage that would only be used to indicate which environment you are in.

**Comment by patphongs** [comment]
This has been resolved by #102
