### ISSUE TITLE
Add "Horizontal" subcategory for card component

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-pattern-library#71]
_Filed as a next step to #47, there are 4 sub-categories for cards. The others should include [Vertical](#72), [Feature](#73), and [Major](#74) cards. Each has its own issue._

**What we're after:**
Adding "Horizontal" as the first Card component sub-category
> Cards
>  - **01 - Horizontal**
>  - 02 - Vertical
>  - 03 - Feature
>  - 04 - Major

**Why we're after it:**
Adding these examples and subcategories will make the card component more comprehensive and up to date in the pattern library, which gives designers and developers a more accurate sense of their options.

**Component preview mockup**
These should include the following examples:

![screen shot 2018-02-26 at 9 20 53 pm](https://user-images.githubusercontent.com/11636908/36707137-0397c60e-1b3b-11e8-922b-2aae6ef7baf6.png)

**Content for notes tab**
_Use the existing note content for both the Horizontal and Vertical categories_
> _Ex: Guide cards on the [Help for candidates and committees landing page](https://www.fec.gov/help-candidates-and-committees/)_
_[Reporting example](https://www.fec.gov/help-candidates-and-committees/filing-reports/48-hour-notices/) cards_
_Legal category cards on the [legal resources landing page](https://www.fec.gov/legal-resources/)_

**Comment by jenniferthibault** [comment]
This issue can be closed when #100 is merged

**Comment by JonellaCulmer** [comment]
This work has been merged, so closing. 

https://fec-pattern-library.app.cloud.gov/components/detail/horizontal-cards.html
