### ISSUE TITLE
Add "Vertical" subcategory for card component

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-pattern-library#72]
_Filed as a next step to #47, there are 4 sub-categories for cards. The others should include [Horizontal](#71), [Feature](#73), and [Major](#74) cards. Each has its own issue._

**What we're after:**
Adding "Vertical" as the second Card component sub-category in the pattern library
> Cards
>  - 01 - Horizontal
>  - **02 - Vertical**
>  - 03 - Feature
>  - 04 - Major

**Why we're after it:**
Adding these examples and subcategories will make the card component more comprehensive and up to date in the pattern library, which gives designers and developers a more accurate sense of their options.

**Component preview mockup**
These should include the following examples:

![screen shot 2018-02-26 at 9 28 45 pm](https://user-images.githubusercontent.com/11636908/36707393-1b163f26-1b3c-11e8-8ac1-6b848f1ed863.png)

**Content for notes tab**
_Use the existing note content for both the Horizontal and Vertical categories_
> _Ex: Candidate profile pages, ["About this candidate" tab](https://www.fec.gov/data/candidate/S2WI00219/?tab=about-candidate)_

**Comment by jenniferthibault** [comment]
This issue can be closed when #100 is merged

**Comment by JonellaCulmer** [comment]
This work has been merged, so closing.

https://fec-pattern-library.app.cloud.gov/components/detail/vertical-cards.html
