### ISSUE TITLE
Add "Major" subcategory for card component

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-pattern-library#74]
_Filed as a next step to #47, there are 4 sub-categories for cards. The others should include [Horizontal](#71), [Vertical](#72), and [Feature](#73) cards. Each has its own issue._

**What we're after:**
Adding "Major" as the fourth Card component sub-category in the pattern library
> Cards
>  - 01 - Horizontal
>  - 02 - Vertical
>  - 03 - Feature
>  - **04 - Major**

**Why we're after it:**
Adding these examples and subcategories will make the card component more comprehensive and up to date in the pattern library, which gives designers and developers a more accurate sense of their options.

**Component preview mockup**
These should include the following examples:

![screen shot 2018-02-26 at 9 29 06 pm](https://user-images.githubusercontent.com/11636908/36707564-d397f56c-1b3c-11e8-99b3-6ee702fc3aee.png)

**Content for notes tab**
> Major cards are a flexible content container. They include a title, contextual copy, and an can include metadata, like an item count. There’s no set restriction on how many major cards should be used in a layout, but more items may require more advanced filtering functionality, since visual scanning becomes more difficult when more items are present.
> _Ex: [Reports about the FEC](https://www.fec.gov/about/reports-about-fec/)_
>
> ### Resources
>Learn more about best practices for cards from the [Nielsen Norman Group](https://www.nngroup.com/articles/cards-component/).

**Comment by jenniferthibault** [comment]
This issue can be closed when #100 is merged

**Comment by JonellaCulmer** [comment]
This work has been merged, so closing.

https://fec-pattern-library.app.cloud.gov/components/detail/major-cards.html
