### ISSUE TITLE
Training on maintaining pattern library expectation with Jonella, Pat & John

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-pattern-library#81]
Training on maintaining pattern library expectation with Jonella, Pat & John

- [ ] Pairing w/Jenn, John, Jonella and Pat

**Comment by jenniferthibault** [comment]
I think this can be closed in favor of assigning the pairing issues from the pattern library this sprint, as we talked about in sprint grooming. We'll be sure to cover maintainability in each session when it's relevant, and can plan to discuss it together as a group at a design sync session.
