### ISSUE TITLE
Add Commissioner page template to page layouts section

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-pattern-library#90]
👯 **Pairing opportunity!** 👯 

To complete mapping the page layouts and templates available in Wagtail, add documentation about the Commissioner page template to the pattern library site.

- [x] Add layout image (compare page visuals with Wagtail component fields, label correspondingly)
- [x] Edit draft documentation, or write new. Include:
  - [x] template introduction
  - [x] component list and notes
  - [x] "When to use" guidance
  - [x] list of example pages  
- [x] Add information to pattern library via implementation PR (w/Jonella too)
  - [x] Re-order page template list to be listed alphabetically

**Comment by JonellaCulmer** [comment]
Below is the layout image of the Commissioner page layout/template for the pattern library. 
At the following link is the relevant pattern library notes that need to be added as well: https://docs.google.com/document/d/1LrumX8Iq0Frn1cnRrIltAqLAzRmGXYnTrGMBe_s1x7M/edit#

![page-commissioner](https://user-images.githubusercontent.com/31663028/37930037-8cff7dc6-310f-11e8-9597-0864fbdbf227.png)

**Comment by jenniferthibault** [comment]
This layout looks 👍  @JonellaCulmer ! I just noticed a typo in the "Commissioner" email/phone/twitter fields though 🙈. I do this one all the time, so many letters! Sorry I didn't catch this yesterday. While your'e in there, if you also want to even out the bio box to end at the same point as the twitter box it will help make the layout look more balanced (though it doesn't _really_ matter, it will make for nicer presentation in the pattern library interface).

@johnnyporkchops we have all the assets ready, are you up for pairing through implementing this today or tomorrow?

**Comment by johnnyporkchops** [comment]
I can pair on this today.

**Comment by JonellaCulmer** [comment]
@jenniferthibault Updated the image in my previous comment ^^

**Comment by jenniferthibault** [comment]
Resolved by #95
